name: ci

on: push

jobs:
  ci: 
    runs-on: ubuntu-latest
    steps:
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials/@v1
        with:
          aws-access-key-id: $({secrets.AWS_ACCESS_KEY_ID})
          aws-secret_access_key: $({secrets.AWS_SECRET_ACCESS_KEY})
          aws-region: us-east-1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm ci
        env:
          CI: true,
        run:
          npm ci
      - name: test
        run: |
          npm test
      - name: deploy
        run: | 
          npm run deploy